FROM node:latest as build
WORKDIR /app
COPY package*.json /app/
RUN yarn install
COPY . .
CMD ["make", "all"]

FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY --from=build /app/nginx/nginx.conf /etc/nginx/nginx.conf
