version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run lint
          command: make lint 
      - run:
          name: Run test
          command: make test
      - run:
          name: Build prod version
          command: make build
  dockerize-and-kubernetize:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Docker login
          command: make docker_login
      - run:
          name: Docker build
          command: make docker_build
      - run:
          name: Docker push
          command: make docker_push
      - run:
          name: Kubernetes deploy
          command: make deploy

workflows:
  version: 2
  full:
    jobs:
      - build_and_test
      - dockerize-and-kubernetize:
          requires:
            - build_and_test
          context: onboarding 