version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Run lint and tests
          command: make lint run-tests
      - run:
          name: Build prod version
          command: make build
  dockerize-and-kubernetize:
    docker:
      - image: cimg/node:17.4.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
          docker_layer_caching: true
      - run:
          name: Docker login
          command: make docker-login
      - run:
          name: Docker build
          command: make docker-build
      - run:
          name: Docker push
          command: make docker-push
      - run:
          name: Kubernetes deploy
          command: make deploy

workflows:
  version: 2
  full:
    jobs:
      - build-and-test
      - dockerize-and-kubernetize:
          requires:
            - build-and-test
          context: onboarding 